New release

diff --git a/control/prerm b/control/prerm
--- a/control/prerm
+++ b/control/prerm
@@ -1,18 +1,49 @@
 #!/bin/sh
 
-# Handle execution as pmPostInstall.script
-if [ -z "$IPKG_OFFLINE_ROOT" ]; then
+SID="org.webosinternals.pulsecontrol.srv"
+
+APPS="/media/cryptofs/apps"
+
+SDIR="${APPS}/usr/palm/services/${SID}"
+
+# Handle execution as pmPreRemove.script
+
+if [ ! -d ${APPS} ]; then
+	echo "Requires webOS 1.3.5 or later"
+	exit 1
+fi
+
+if [ -z "${IPKG_OFFLINE_ROOT}" ]; then
   IPKG_OFFLINE_ROOT=/media/cryptofs/apps
   mount -o remount,rw /
 fi
 
-SRV_ID=org.webosinternals.pulsecontrol.srv
-SRV_DIR=/media/cryptofs/apps/usr/palm/services/${SRV_ID}
+# Remove the upstart configuration
 
-rm -f /var/cache/configurator/_media_cryptofs_apps_usr_palm_services_${SRV_ID}_configuration_db_permissions_${SRV_ID}
+rm -f /var/palm/event.d/${SID}
 
-rm -f /var/palm/event.d/${SRV_ID}
+# Remove the ls2 configuration
 
-#/usr/bin/pkill switcher.srv.js || true
+rm -f /var/palm/ls2/roles/prv/${SID}.json
+rm -f /var/palm/ls2/roles/pub/${SID}.json
 
-/usr/bin/ls-control scan-services || true
+# Remove the dbus service configuration
+
+rm -f /var/palm/ls2/services/prv/${SID}.service
+rm -f /var/palm/ls2/services/pub/${SID}.service
+
+# Stop the JS service if running
+
+/usr/bin/luna-send -n 1 palm://${SID}/__quit '{}'
+
+#
+# Cleanup the JS service here due to WebOS bugs
+#
+
+rm -f /var/cache/configurator/*webosinternals.pulsecontrol*
+
+rm -f /var/palm/ls2/roles/*/*webosinternals.pulsecontrol*
+
+rm -f /var/palm/ls2/services/*/*webosinternals.pulsecontrol*
+
+exit 0
